id = "apache-avro"
name = "Apache Avro"
version = "0.2.0"
schema_version = 1
authors = ["Victor Quiroz <git@victorhqc.com>"]
description = "Apache Avro support for the IDL Language"
repository = "https://github.com/victorhqc/zed-apache-avro"

[grammars.apache_avro]
repository = "https://github.com/victorhqc/tree-sitter-apache-avro"
commit = "9935af1fb3447c7eb07f71e16023fda95beafd08"
